// <auto-generated />
namespace Chick.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DodanieKlucza : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanieKlucza));
        
        string IMigrationMetadata.Id
        {
            get { return "201805291635255_DodanieKlucza"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
